name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: |
        cd /tmp
        wget -q -O carrot2.zip https://github.com/carrot2/carrot2/releases/download/release%2F4.0.4/carrot2-4.0.4.zip
        unzip carrot2.zip
        cd carrot2-4.0.4
        ./dcs.sh &
        for i in {1..12}; do wget -O- -v http://127.0.0.1:8080/ && break || sleep 5; done
    - run: bundle exec rake test
